------------------------------------------------------------
-- CATEGORY
------------------------------------------------------------
CREATE TABLE Category (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL UNIQUE
);

------------------------------------------------------------
-- PRODUCT
------------------------------------------------------------
CREATE TABLE Product (
    product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(150) NOT NULL,
    description   VARCHAR2(500),
    price         NUMBER(10,2) NOT NULL CHECK (price >= 0),
    category_id   NUMBER NOT NULL,
    stock_quantity NUMBER DEFAULT 0 CHECK (stock_quantity >= 0),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES Category(category_id)
);

------------------------------------------------------------
-- CUSTOMER
------------------------------------------------------------
CREATE TABLE Customer (
    customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(100) NOT NULL,
    last_name     VARCHAR2(100) NOT NULL,
    email         VARCHAR2(200) NOT NULL UNIQUE,
    phone         VARCHAR2(50),
    address       VARCHAR2(400)
);

------------------------------------------------------------
-- ORDER
------------------------------------------------------------
CREATE TABLE CustomerOrder (
    order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER NOT NULL,
    order_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status        VARCHAR2(50) DEFAULT 'pending',

    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id)
);

------------------------------------------------------------
-- ORDER ITEM
------------------------------------------------------------
CREATE TABLE OrderItem (
    order_item_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER NOT NULL,
    product_id      NUMBER NOT NULL,
    quantity        NUMBER NOT NULL CHECK (quantity > 0),
    unit_price      NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_orderitem_order
        FOREIGN KEY (order_id)
        REFERENCES CustomerOrder(order_id),

    CONSTRAINT fk_orderitem_product
        FOREIGN KEY (product_id)
        REFERENCES Product(product_id)
);

------------------------------------------------------------
-- PAYMENT (1:1 with Order)
------------------------------------------------------------
CREATE TABLE Payment (
    payment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER NOT NULL UNIQUE,
    amount        NUMBER(10,2) NOT NULL CHECK (amount >= 0),
    method        VARCHAR2(50) NOT NULL,
    paid_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
        REFERENCES CustomerOrder(order_id)
);

------------------------------------------------------------
-- SHIPPING (0..1 per order)
------------------------------------------------------------
CREATE TABLE Shipping (
    shipping_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER NOT NULL UNIQUE, 
    employee_id   NUMBER NOT NULL,
    shipped_at    TIMESTAMP,
    delivery_date TIMESTAMP,
    tracking_code VARCHAR2(100),

    CONSTRAINT fk_shipping_order
        FOREIGN KEY (order_id)
        REFERENCES CustomerOrder(order_id)
);

------------------------------------------------------------
-- EMPLOYEE
------------------------------------------------------------
CREATE TABLE Employee (
    employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(100) NOT NULL,
    last_name     VARCHAR2(100) NOT NULL,
    role          VARCHAR2(100)
);

------------------------------------------------------------
-- STOCK MOVEMENT
------------------------------------------------------------
CREATE TABLE StockMovement (
    movement_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    NUMBER NOT NULL,
    employee_id   NUMBER NOT NULL,
    quantity      NUMBER NOT NULL,
    movement_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reason        VARCHAR2(200),

    CONSTRAINT fk_movement_product
        FOREIGN KEY (product_id)
        REFERENCES Product(product_id),

    CONSTRAINT fk_movement_employee
        FOREIGN KEY (employee_id)
        REFERENCES Employee(employee_id)
);

------------------------------------------------------------
-- REVIEW
------------------------------------------------------------
CREATE TABLE Review (
    review_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    NUMBER NOT NULL,
    customer_id   NUMBER NOT NULL,
    rating        NUMBER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_comment VARCHAR2(1000),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_review_product
        FOREIGN KEY (product_id)
        REFERENCES Product(product_id),

    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id)
);
